export const homeAbout = [
    {
      id: 1,
      cover: "https://img.icons8.com/dotty/80/000000/storytelling.png",
      title: "Safeguard workers",
      desc: "Identify risk to personnel and enable operations leaders to make data-driven decisions to eliminate hazards and accidents.",
    },
    {
      id: 1,
      cover: "https://img.icons8.com/ios/80/000000/diploma.png",
      title: "Optimize efficiency",
      desc: "Pinpoint critical issues impacting productivity and provide insights to systematically improve operational performance",
    },
    {
      id: 1,
      cover: "https://img.icons8.com/ios/80/000000/athlete.png",
      title: "Predict hazards",
      desc: "Our predictive analytics engine detects anomalies and identifies emerging risks across complex industrial environments.",
    },
  ]

  export const blog = [
    {
      id: 1,
      type: "admin",
      date: "JAN. 18, 2021",
      com: "3 COMMENTS ",
      title: "Build your Dream Software & Engineering Career",
      desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
      cover: "../images/blog/b1.webp",
    },
    {
      id: 2,
      type: "admin",
      date: "API. 25, 2022",
      com: "5 COMMENTS ",
      title: "Build your Dream Software & Engineering Career",
      desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
      cover: "../images/blog/b2.webp",
    },
    {
      id: 3,
      type: "user",
      date: "MAY. 15, 2022",
      com: "10 COMMENTS ",
      title: "Build your Dream Software & Engineering Career",
      desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
      cover: "../images/blog/b3.webp",
    },
    {
      id: 4,
      type: "admin",
      date: "JAN. 02, 2022",
      com: "3 COMMENTS ",
      title: "Build your Dream Software & Engineering Career",
      desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
      cover: "../images/blog/b4.webp",
    },
    {
      id: 5,
      type: "admin",
      date: "DEC. 14, 2022",
      com: "3 COMMENTS ",
      title: "Build your Dream Software & Engineering Career",
      desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
      cover: "../images/blog/b5.webp",
    },
    {
      id: 6,
      type: "user",
      date: "JAN. 18, 2021",
      com: "12 COMMENTS ",
      title: "Build your Dream Software & Engineering Career",
      desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
      cover: "../images/blog/b6.webp",
    },
  ]
  export const testimonal = [
    {
      id: 1,
      name: "Aikins Danso",
      post: "MARKETING MANAGER",
      desc: "Using SafeSmartTech reduced accidents by 20% last year. Highly recommended!",
      cover: "./images/testo/t1.webp",
    },
    {
      id: 2,
      name: "Jimah Ibrahim",
      post: "Made my factory safer",
      desc: "The AI analytics helped me identify and mitigate risks I didn't even know existed.",
      cover: "./images/testo/t2.webp",
    },
    {
      id: 3,
      name: "Emelia Quaye",
      post: "MARKETING MANAGER",
      desc: "If not for SafeSmartTech's real-time alerts, a collapsed beam would have killed someone.",
      cover: "./images/testo/t3.webp",
    },
  ]